/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalcsIndexRouteImport } from './routes/calcs/index'
import { Route as CalcsDcaRouteImport } from './routes/calcs/dca'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsIndexRoute = CalcsIndexRouteImport.update({
  id: '/calcs/',
  path: '/calcs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsDcaRoute = CalcsDcaRouteImport.update({
  id: '/calcs/dca',
  path: '/calcs/dca',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calcs/dca': typeof CalcsDcaRoute
  '/calcs': typeof CalcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calcs/dca': typeof CalcsDcaRoute
  '/calcs': typeof CalcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calcs/dca': typeof CalcsDcaRoute
  '/calcs/': typeof CalcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/calcs/dca' | '/calcs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/calcs/dca' | '/calcs'
  id: '__root__' | '/' | '/about' | '/calcs/dca' | '/calcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CalcsDcaRoute: typeof CalcsDcaRoute
  CalcsIndexRoute: typeof CalcsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/': {
      id: '/calcs/'
      path: '/calcs'
      fullPath: '/calcs'
      preLoaderRoute: typeof CalcsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/dca': {
      id: '/calcs/dca'
      path: '/calcs/dca'
      fullPath: '/calcs/dca'
      preLoaderRoute: typeof CalcsDcaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CalcsDcaRoute: CalcsDcaRoute,
  CalcsIndexRoute: CalcsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
